// 프로젝트를 추가하거나 수정할 때는 이 배열만 편집하면 됩니다.
window.PORTFOLIO_PROJECTS = [
  {
    title: "Dear My Prince",
    status: "진행 중",
    graphic: "3D",
    view: "사이드뷰",
    genre: "액션, 플랫포머",
    engine: "Unity, URP, Forward",
    purpose: "청강문화산업대학교 졸업작품",
    period: "2025.03.02 ~ 2025.11.20",
    team: "14명",
    summary: "마우스 인터랙션을 활용해 플레이하는 액션 게임입니다.",
    image: "assets/portfolio/dear-my-prince.png",
    featured: true,
    links: [
      {
        label: "2학기 기말영상",
        url: "https://youtu.be/9AStqEIan_w?si=XLIkz3b562lcHd6M",
      },
      {
        label: "1학기 기말영상",
        url: "https://youtu.be/IhRAN0lDSNE?si=25B9kBBgVb5_esF1",
      },
    ],
  },
  {
    title: "꽃의소녀",
    status: "개발완료",
    graphic: "3D",
    view: "쿼터뷰",
    genre: "어드벤처, 퍼즐",
    engine: "Unreal, Deferred",
    purpose: "2024년 청강문화산업대학교 2학년 2학기 학기작",
    period: "14주",
    team: "14명",
    summary: "쓰레기를 청소하고 숲을 정화하며 치유와 뿌듯함을 전달하는 게임입니다.",
    image: "assets/portfolio/flower-girl.png",
    links: [
      {
        label: "영상",
        url: "https://youtu.be/WgAmVcwEapI?si=LitLsF7gJzd4_u6z",
      },
    ],
  },
  {
    title: "요리조리",
    status: "개발완료",
    graphic: "3D",
    view: "VR",
    genre: "시뮬레이션, 퍼즐",
    engine: "Unity, URP, Forward",
    purpose: "2024 청강문화산업대학교 AR/VR 페스티벌 참가",
    period: "2024.07.01 ~ 2024.08.23",
    team: "13명",
    summary: "플레이어를 방해하는 기믹 재료를 처리하며 요리를 완성하는 VR 게임입니다.",
    image: "assets/portfolio/yorijori.png",
    links: [
      {
        label: "영상",
        url: "https://youtu.be/h7lnSOAWpxM?si=_vz6FD4Aeqfo89GA",
      },
      {
        label: "GitHub",
        url: "https://github.com/aldkl/Yorijori",
      },
    ],
  },
  {
    title: "Memoria",
    status: "개발완료",
    graphic: "3D",
    view: "사이드뷰",
    genre: "퍼즐, 플랫포머",
    engine: "Unity, Built-in, Forward",
    purpose: "2021 청강문화산업대학교 긴긴게임잼",
    period: "2021.05.02 ~ 2021.07.21",
    team: "7명",
    summary: "현실과 가상세계를 번갈아 보며 역경을 헤쳐나가는 플랫포머 게임입니다.",
    image: "assets/portfolio/memoria.png",
    links: [
      {
        label: "GitHub",
        url: "https://github.com/aldkl/Memoria",
      },
      {
        label: "Build",
        url: "https://drive.google.com/file/d/153zfTm-pG8CxlE_F4easZCBmE6oneljm/view?usp=sharing",
      },
    ],
  },
  {
    title: "ColorXLight",
    status: "개발완료",
    graphic: "2D",
    view: "사이드뷰",
    genre: "플랫포머",
    engine: "Unity",
    purpose: "2021 청강문화산업대학교 게임프로젝트입문",
    period: "2021.05.11 ~ 2021.06.07",
    team: "4명",
    summary: "맵에 퍼져있는 3개의 색상을 모아 다음 스테이지로 넘어가는 퍼즐 플랫포머입니다.",
    image: "assets/portfolio/colorxlight.png",
    links: [
      {
        label: "GitHub",
        url: "https://github.com/aldkl/ColorXLight",
      },
      {
        label: "Build",
        url: "https://drive.google.com/file/d/1S_sWPBKH97D-rzHc9WcwcBzyM-cQ1W7e/view?usp=drive_link",
      },
    ],
  },
  {
    title: "Sea in the Seawer",
    status: "개발완료",
    graphic: "2D",
    view: "쿼터뷰",
    genre: "어드벤처",
    engine: "Unity, URP, Forward",
    purpose: "2020 대한민국 청소년 게임잼",
    period: "",
    team: "",
    summary: "어둠 속에서 소리를 잘 듣고 앞을 헤쳐나가는 어드벤처 게임입니다.",
    image: "assets/portfolio/sea-in-the-seawer.png",
    links: [
      {
        label: "Build",
        url: "https://drive.google.com/file/d/1pBsXLx-jSrCeH_TQv7rbWDsO9N_kxe36/view?usp=drive_link",
      },
    ],
  },
  {
    title: "애니멀드래프트",
    status: "개발완료",
    graphic: "3D",
    view: "백뷰",
    genre: "레이싱, 시뮬레이션",
    engine: "Built-in, Forward",
    purpose: "2019 한국게임과학고등학교 2학년 2학기 팀프로젝트",
    period: "2019.09 ~ 2020.01",
    team: "3명",
    summary: "카트라이더처럼 만들어 보기 위해 제작한 레이싱 연습작입니다.",
    image: "assets/portfolio/animaldraft.png",
    links: [
      {
        label: "GitHub",
        url: "https://github.com/aldkl/AnimalDraft",
      },
    ],
  },
  {
    title: "동방환상록 모작",
    status: "개발완료",
    graphic: "2D",
    view: "탑뷰",
    genre: "슈팅",
    engine: "Unity, Built-in, Forward",
    purpose: "2019 한국게임과학고등학교 팀장 선발을 위한 게임",
    period: "2019.05",
    team: "프로그래머 1명",
    summary: "동방풍신록을 모작하며 UI, 로딩, 몬스터 움직임을 원작과 유사하게 구현한 슈팅 게임입니다.",
    image: "assets/portfolio/touhou-remake.png",
    links: [
      {
        label: "Build",
        url: "https://drive.google.com/file/d/1O79SPSuusA2G4p4VV6oJpO096U_5MYL2/view?usp=drive_link",
      },
    ],
  },
  {
    title: "킬러킴",
    status: "개발완료",
    graphic: "2D",
    view: "쿼터뷰",
    genre: "액션",
    engine: "OpenGL",
    purpose: "2018 한국게임과학고등학교 학교내 게임제작대회 참여작",
    period: "2018.10 ~ 2019.01",
    team: "3명",
    summary: "상대방의 총알을 흡수해 다시 쏘는 액션 게임입니다.",
    image: "assets/portfolio/killerkim.png",
    links: [
      {
        label: "GitHub",
        url: "https://github.com/aldkl/KillerKim",
      },
      {
        label: "Build",
        url: "https://drive.google.com/file/d/1_McME6j1biNXwxl6YqJtmKdVFBYNgzCr/view?usp=drive_link",
      },
    ],
  },
];
