// 새 항목을 추가할 때는 category, slug, title, tags, image, gallery를 먼저 채우면 됩니다.
// role/problem/solution/learned는 상세 페이지에서 "내가 한 작업"과 "문제 해결/배운점"으로 표시됩니다.
window.PORTFOLIO_ITEMS = [
  {
    category: "project",
    slug: "dear-my-prince",
    title: "Dear My Prince",
    status: "개발완료",
    tags: ["3D", "사이드뷰", "액션", "플랫포머", "Unity", "URP"],
    purpose: "청강문화산업대학교 졸업작품",
    period: "2025.03.02 ~ 2025.11.20",
    team: "14명",
    parts: ["PM", "프로그래머", "TA", "애니메이터", "이펙터"],
    summary: "마우스 인터랙션을 활용해 플레이하는 액션 게임입니다.",
    role: "PM으로 프로젝트 진행 상황을 정리하고 파트 간 작업 흐름을 맞췄습니다. 프로그래머로서는 마우스 인터랙션 기반 기능 구현과 게임 진행에 필요한 기능 코드를 작성했고, TA로서 캐릭터 표현에 필요한 쉐이더와 그래픽 기술 작업을 담당했습니다. 애니메이터로 캐릭터 동작을 제작하고, 이펙터로 전투와 상호작용에 필요한 이펙트를 제작했습니다. 또한 FMOD 연동과 작업일지 정리도 함께 진행했습니다.",
    problem: "졸업작품 규모에서 여러 파트의 결과물이 동시에 들어오며 캐릭터 표현, 사운드, 기능 구현의 기준을 맞춰야 했습니다.",
    solution: "작업 내용을 기능별로 분리하고, 애니메이션/쉐이더/사운드가 서로 충돌하지 않도록 테스트 단위를 나눠 통합했습니다.",
    learned: "파트 간 의사소통과 작업 기록이 큰 프로젝트의 품질을 안정시키는 핵심이라는 점을 배웠습니다.",
    image: "assets/portfolio/dear-my-prince.png",
    featured: true,
    gallery: ["assets/projects/dear-my-prince/01.png"],
    links: [
      { label: "2학기 기말영상", url: "https://youtu.be/9AStqEIan_w?si=XLIkz3b562lcHd6M" },
      { label: "1학기 기말영상", url: "https://youtu.be/IhRAN0lDSNE?si=25B9kBBgVb5_esF1" },
    ],
  },
  {
    category: "project",
    slug: "flower-girl",
    title: "꽃의소녀",
    status: "개발완료",
    tags: ["3D", "쿼터뷰", "어드벤처", "퍼즐", "Unreal"],
    purpose: "2024년 청강문화산업대학교 2학년 2학기 학기작",
    period: "14주",
    team: "14명",
    parts: ["PD", "프로그래머", "TA"],
    summary: "쓰레기를 청소하고 숲을 정화하며 치유와 뿌듯함을 전달하는 게임입니다.",
    role: "PD로 게임의 핵심 경험과 개발 방향을 정리하고, 팀의 콘텐츠 범위와 작업 우선순위를 조율했습니다. 프로그래머로서 흡입을 이용한 청소 플레이와 퍼즐 진행에 필요한 기능 구현에 참여했고, TA로서 그래픽 표현과 기술적 구현 사이의 조율을 담당했습니다. 제한된 그래픽 리소스 안에서 몬스터와 NPC를 최소화하고, 정화된 숲을 보며 힐링과 뿌듯함을 느끼는 방향으로 프로젝트를 정리했습니다.",
    problem: "팀 리소스와 개발 기간이 제한되어 몬스터, NPC, 퍼즐 범위를 계속 조정해야 했습니다.",
    solution: "흡입을 이용한 청소와 정화된 숲을 바라보는 감정에 집중하도록 콘텐츠를 정리했습니다.",
    learned: "재미의 방향을 한 문장으로 정리하고 팀이 공유해야 개발 중 흔들림을 줄일 수 있다는 점을 배웠습니다.",
    image: "assets/portfolio/flower-girl.png",
    gallery: ["assets/projects/flower-girl/01.png"],
    links: [{ label: "영상", url: "https://youtu.be/WgAmVcwEapI?si=LitLsF7gJzd4_u6z" }],
  },
  {
    category: "project",
    slug: "yorijori",
    title: "요리조리",
    status: "개발완료",
    tags: ["3D", "VR", "시뮬레이션", "퍼즐", "Unity", "URP"],
    purpose: "2024 청강문화산업대학교 AR/VR 페스티벌 참가",
    period: "2024.07.01 ~ 2024.08.23",
    team: "13명",
    parts: ["프로그래머"],
    summary: "기믹 재료를 처리하며 요리를 완성하는 VR 게임입니다.",
    role: "프로그래머로 요리 레시피, 재료 상태, 접시 완성 로직을 구현했습니다. 재료가 잘림, 가열, 섞임, 실패 상태를 가질 수 있도록 Ingredient 구조를 만들고, 접시에 올라간 재료와 등록된 레시피를 비교해 요리 완성 여부를 판단하도록 제작했습니다. VR 기기 연동은 Unity XR 기능을 사용해 구현했으며, 많은 요리와 재료가 빠르게 추가될 수 있도록 리스트 기반으로 데이터를 관리했습니다.",
    problem: "요리와 재료 수가 계속 바뀔 수 있어 하드코딩하면 수정 비용이 커지는 구조였습니다.",
    solution: "Recipe와 Ingredient를 리스트 기반 데이터로 구성해 엔진에서 쉽게 조정할 수 있게 만들었습니다.",
    learned: "콘텐츠 수가 늘어나는 게임에서는 처음부터 데이터 확장성을 확보해야 한다는 점을 배웠습니다.",
    image: "assets/portfolio/yorijori.png",
    gallery: ["assets/projects/yorijori/01.png"],
    links: [
      { label: "영상", url: "https://youtu.be/h7lnSOAWpxM?si=_vz6FD4Aeqfo89GA" },
      { label: "GitHub", url: "https://github.com/aldkl/Yorijori" },
    ],
  },
  {
    category: "project",
    slug: "memoria",
    title: "Memoria",
    status: "개발완료",
    tags: ["3D", "사이드뷰", "퍼즐", "플랫포머", "Unity"],
    purpose: "2021 청강문화산업대학교 긴긴게임잼",
    period: "2021.05.02 ~ 2021.07.21",
    team: "7명",
    parts: ["프로그래머"],
    summary: "현실과 가상세계를 번갈아 보며 역경을 헤쳐나가는 플랫포머 게임입니다.",
    role: "프로그래머로 캐릭터 상태에 따른 애니메이션 전환과 배경 오브젝트 텍스처 전환 구조를 구현했습니다. V, N, VN 상태에 따라 캐릭터 애니메이션 이름을 규칙적으로 바꾸고, 배경 오브젝트의 태그에 따라 상태별 텍스처가 적용되도록 만들었습니다. 현실과 가상세계가 보이는 방식이 플레이 규칙과 연결되도록 상태 관리 구조를 작성했습니다.",
    problem: "한쪽 눈 상태에 따라 캐릭터와 배경 표현이 동시에 달라져야 했습니다.",
    solution: "V, N, VN 상태명을 기준으로 애니메이션과 텍스처를 관리했습니다.",
    learned: "상태 이름 규칙을 명확히 만들면 리소스와 코드 양쪽 관리가 쉬워진다는 점을 배웠습니다.",
    image: "assets/portfolio/memoria.png",
    gallery: ["assets/projects/memoria/01.png", "assets/projects/memoria/02.png", "assets/projects/memoria/03.png", "assets/projects/memoria/04.png"],
    links: [
      { label: "GitHub", url: "https://github.com/aldkl/Memoria" },
      { label: "Build", url: "https://drive.google.com/file/d/153zfTm-pG8CxlE_F4easZCBmE6oneljm/view?usp=sharing" },
    ],
  },
  {
    category: "project",
    slug: "colorxlight",
    title: "ColorXLight",
    status: "개발완료",
    tags: ["2D", "사이드뷰", "플랫포머", "Unity"],
    purpose: "2021 청강문화산업대학교 게임프로젝트입문",
    period: "2021.05.11 ~ 2021.06.07",
    team: "4명",
    parts: ["프로그래머"],
    summary: "3개의 색상을 모아 다음 스테이지로 넘어가는 퍼즐 플랫포머입니다.",
    role: "프로그래머로 상호작용 오브젝트 구조, 램프 퍼즐, 문 개방 로직을 구현했습니다. Interactable 추상 클래스를 만들고, 이를 상속한 LightControl 클래스로 램프를 켜는 퍼즐을 제작했습니다. 램프 상태를 검사해 조건이 충족되면 문이 열리고 플랫폼이 움직이도록 구성했습니다.",
    problem: "여러 상호작용 오브젝트가 생기며 공통 규칙을 분리할 필요가 있었습니다.",
    solution: "Interactable 추상 클래스를 만들고, LightControl 등 세부 오브젝트가 이를 상속하게 구성했습니다.",
    learned: "초기 구조를 조금만 분리해도 이후 퍼즐 추가가 쉬워진다는 점을 배웠습니다.",
    image: "assets/portfolio/colorxlight.png",
    gallery: ["assets/projects/colorxlight/01.png", "assets/projects/colorxlight/02.png", "assets/projects/colorxlight/03.png", "assets/projects/colorxlight/04.png"],
    links: [
      { label: "GitHub", url: "https://github.com/aldkl/ColorXLight" },
      { label: "Build", url: "https://drive.google.com/file/d/1S_sWPBKH97D-rzHc9WcwcBzyM-cQ1W7e/view?usp=drive_link" },
    ],
  },
  {
    category: "project",
    slug: "sea-in-the-seawer",
    title: "Sea in the Seawer",
    status: "개발완료",
    tags: ["2D", "쿼터뷰", "어드벤처", "Unity", "URP"],
    purpose: "2020 대한민국 청소년 게임잼",
    period: "",
    team: "",
    parts: ["프로그래머"],
    summary: "어둠 속에서 소리를 듣고 앞을 헤쳐나가는 어드벤처 게임입니다.",
    role: "프로그래머로 시야가 제한된 상황에서 소리를 단서로 진행하는 플레이 경험을 구현했습니다. 화면 정보를 적게 제공하는 대신 플레이어가 소리와 주변 단서를 통해 길을 찾아가도록 구성했습니다. 게임잼 기간 안에 핵심 규칙이 전달되도록 기능 범위를 좁혀 제작했습니다.",
    problem: "화면 정보가 제한될 때도 플레이어가 방향을 잃지 않게 해야 했습니다.",
    solution: "소리와 제한된 시각 정보를 진행 단서로 사용해 게임잼 주제를 살렸습니다.",
    learned: "정보를 일부러 덜 보여주는 방식도 게임 규칙이 될 수 있다는 점을 배웠습니다.",
    image: "assets/portfolio/sea-in-the-seawer.png",
    gallery: ["assets/projects/sea-in-the-seawer/01.png", "assets/projects/sea-in-the-seawer/02.png", "assets/projects/sea-in-the-seawer/03.png"],
    links: [{ label: "Build", url: "https://drive.google.com/file/d/1pBsXLx-jSrCeH_TQv7rbWDsO9N_kxe36/view?usp=drive_link" }],
  },
  {
    category: "project",
    slug: "animaldraft",
    title: "애니멀드래프트",
    status: "개발완료",
    tags: ["3D", "백뷰", "레이싱", "시뮬레이션", "Built-in"],
    purpose: "2019 한국게임과학고등학교 2학년 2학기 팀프로젝트",
    period: "2019.09 ~ 2020.01",
    team: "3명",
    parts: ["PD", "팀장", "프로그래머"],
    summary: "카트라이더처럼 만들어 보기 위해 제작한 레이싱 연습작입니다.",
    role: "PD와 팀장으로 프로젝트 방향과 팀 작업을 관리했고, 프로그래머로 레이싱 게임의 주행, 카메라, 게임 진행 기능을 구현했습니다. 카트라이더 같은 백뷰 레이싱 게임을 목표로 삼고, 속도감과 조작감을 맞추기 위해 이동과 카메라 감각을 반복적으로 조정했습니다. 팀 프로젝트 안에서 기획, 그래픽 파트와 필요한 기능을 조율하며 제작했습니다.",
    problem: "레이싱 게임의 속도감과 조작감을 직접 구현하며 기준을 잡아야 했습니다.",
    solution: "상용 레이싱 게임의 느낌을 참고하며 카메라와 이동감을 반복 조정했습니다.",
    learned: "장르 레퍼런스를 분석하고 직접 재현해 보는 과정이 구현 감각을 키운다는 점을 배웠습니다.",
    image: "assets/portfolio/animaldraft.png",
    gallery: ["assets/projects/animaldraft/01.png", "assets/projects/animaldraft/02.png", "assets/projects/animaldraft/03.png"],
    links: [{ label: "GitHub", url: "https://github.com/aldkl/AnimalDraft" }],
  },
  {
    category: "project",
    slug: "touhou-remake",
    title: "동방환상록 모작",
    status: "개발완료",
    tags: ["2D", "탑뷰", "슈팅", "Unity", "Built-in"],
    purpose: "2019 한국게임과학고등학교 팀장 선발을 위한 게임",
    period: "2019.05",
    team: "프로그래머 1명",
    parts: ["프로그래머"],
    summary: "동방풍신록을 모작하며 UI, 로딩, 몬스터 움직임을 구현한 슈팅 게임입니다.",
    role: "UI 애니메이션, 로딩 연출, 몬스터 이동 경로와 페이즈 구현을 맡았습니다.",
    problem: "약 6일 안에 원작과 비슷한 많은 움직임을 구현해야 했습니다.",
    solution: "iTween 경로를 미리 만들고 몬스터 생성 이후 경로를 연결하는 방식으로 제작 시간을 줄였습니다.",
    learned: "짧은 기간에는 직접 물리나 보간을 모두 만들기보다 검증된 도구를 적절히 쓰는 판단이 중요하다는 점을 배웠습니다.",
    image: "assets/portfolio/touhou-remake.png",
    gallery: ["assets/projects/touhou-remake/01.png", "assets/projects/touhou-remake/02.png", "assets/projects/touhou-remake/03.png", "assets/projects/touhou-remake/04.png"],
    links: [{ label: "Build", url: "https://drive.google.com/file/d/1O79SPSuusA2G4p4VV6oJpO096U_5MYL2/view?usp=drive_link" }],
  },
  {
    category: "project",
    slug: "killerkim",
    title: "킬러킴",
    status: "개발완료",
    tags: ["2D", "쿼터뷰", "액션", "OpenGL"],
    purpose: "2018 한국게임과학고등학교 학교내 게임제작대회 참여작",
    period: "2018.10 ~ 2019.01",
    team: "3명",
    parts: ["PD", "팀장", "프로그래머"],
    summary: "상대방의 총알을 흡수해 다시 쏘는 액션 게임입니다.",
    role: "PD와 팀장으로 프로젝트 방향과 팀 작업을 관리했고, 프로그래머로 OpenGL 기반 게임 구현과 전투 규칙 제작을 맡았습니다. 상대방의 총알을 흡수해 다시 발사하는 핵심 규칙을 중심으로 조작, 전투 흐름, 피드백을 구성했습니다. 팀원들과 역할을 나누고 대회 제출을 목표로 플레이 가능한 형태까지 제작했습니다.",
    problem: "흡수와 반격이라는 핵심 규칙이 명확하게 보이도록 전투 흐름을 만들어야 했습니다.",
    solution: "총알 흡수와 발사를 중심 규칙으로 두고, 조작과 피드백을 단순하게 유지했습니다.",
    learned: "핵심 규칙 하나가 분명하면 작은 프로젝트도 플레이 목표가 선명해진다는 점을 배웠습니다.",
    image: "assets/portfolio/killerkim.png",
    gallery: ["assets/projects/killerkim/01.png", "assets/projects/killerkim/02.png", "assets/projects/killerkim/03.png"],
    links: [
      { label: "GitHub", url: "https://github.com/aldkl/KillerKim" },
      { label: "Build", url: "https://drive.google.com/file/d/1_McME6j1biNXwxl6YqJtmKdVFBYNgzCr/view?usp=drive_link" },
    ],
  },
  {
    category: "freelance",
    slug: "capstone-lighting",
    title: "캡스톤Lighting",
    status: "개발완료",
    tags: ["3D", "VR", "VRC", "Lighting", "Unity", "Built-in"],
    purpose: "캡스톤 전시를 위한 VRC 맵",
    period: "2024.05",
    team: "1명",
    summary: "전시용 VRC 맵의 최적화, 라이팅, 머티리얼, 베이킹을 작업했습니다.",
    role: "VRC 맵의 라이팅 세팅, 머티리얼 적용, 베이크와 최적화 전반을 담당했습니다.",
    problem: "한 씬 안에 5개 구역이 있고, 디렉셔널 라이트와 카메라 노출 문제가 섞여 있었습니다.",
    solution: "구역별 라이트 조건을 절충하고, Far/Near 값과 Shadow 옵션을 조정해 몰입을 해치는 요소를 줄였습니다.",
    learned: "VRC처럼 제약이 큰 환경에서는 라이트맵 UV와 그림자 옵션을 초기에 확인해야 한다는 점을 배웠습니다.",
    image: "assets/works/capstone-lighting/01.png",
    gallery: ["assets/works/capstone-lighting/01.png", "assets/works/capstone-lighting/02.png", "assets/works/capstone-lighting/03.png", "assets/works/capstone-lighting/04.png"],
    links: [],
  },
  {
    category: "freelance",
    slug: "tabibuntu",
    title: "타비분투",
    status: "개발완료",
    tags: ["2D", "사이드뷰", "레이싱", "Unity", "URP"],
    purpose: "타비 팬게임 고군분투",
    period: "2024.05.20 ~ 2024.06.07",
    team: "프로그래밍 1명",
    summary: "고군분투 스타일의 타비 팬게임 외주 작업입니다.",
    role: "스페셜 코인, 저장/불러오기, 그래플링, 타일맵 기반 코인 생성 기능을 구현했습니다.",
    problem: "러너 게임 특성상 코인이 많고, 직접 배치하면 수정과 레벨디자인 비용이 컸습니다.",
    solution: "타일맵에 찍어둔 타일을 시작 시 코인 프리팹으로 변환하는 스포너를 만들었습니다.",
    learned: "레벨디자인 반복이 많은 기능은 에디터 친화적인 제작 방식으로 바꿔야 유지보수가 쉬워집니다.",
    image: "assets/works/tabibuntu/01.png",
    gallery: ["assets/works/tabibuntu/01.png", "assets/works/tabibuntu/02.png"],
    links: [
      { label: "영상", url: "https://youtu.be/pRFWinWKeCc?si=DmTFUY1CNytaJXId&t=18488" },
      { label: "GitHub", url: "https://github.com/aldkl/Tabibuntu" },
    ],
  },
  {
    category: "freelance",
    slug: "accessibility-showroom",
    title: "장애인 기구 전시장",
    status: "개발완료",
    tags: ["3D", "VR", "전시장", "Lighting", "Unity", "URP"],
    purpose: "전북 메타버스 전시장 외주",
    period: "2023.12",
    team: "",
    summary: "다양한 장애인을 위한 제품 전시장 라이팅 및 머티리얼 작업입니다.",
    role: "라이팅, 머티리얼 생성과 적용을 담당했습니다.",
    problem: "전시장 조명 수가 많아 기존 Forward 파이프라인의 동적 라이트 제한이 문제가 됐습니다.",
    solution: "Forward+ 파이프라인을 활용해 많은 동적 라이트를 사용할 수 있게 구성했습니다.",
    learned: "VR 플랫폼에서는 보기 좋은 그림자보다 성능과 사용 목적에 맞는 조명 선택이 중요하다는 점을 배웠습니다.",
    image: "assets/works/accessibility-showroom/01.png",
    gallery: ["assets/works/accessibility-showroom/01.png", "assets/works/accessibility-showroom/02.png", "assets/works/accessibility-showroom/03.png"],
    links: [],
  },
  {
    category: "freelance",
    slug: "et-boardroom",
    title: "ET BordRoom",
    status: "개발완료",
    tags: ["3D", "1인칭", "Lighting", "Unity", "URP"],
    purpose: "외주 작업",
    period: "",
    team: "프로그래머 1명",
    summary: "회의실 씬의 라이팅과 머티리얼을 구성한 외주 작업입니다.",
    role: "하나의 씬에 대한 라이팅, 머티리얼 생성과 적용을 맡았습니다.",
    problem: "클라이언트가 원하는 구도와 조명 분위기에 맞춰 결과물을 제작해야 했습니다.",
    solution: "요구 구도를 기준으로 라이트 배치와 머티리얼 톤을 맞춰 작업했습니다.",
    learned: "외주 작업에서는 기술 구현뿐 아니라 의뢰자의 기준을 정확히 맞추는 과정이 중요하다는 점을 배웠습니다.",
    image: "assets/works/et-boardroom/01.png",
    gallery: ["assets/works/et-boardroom/01.png", "assets/works/et-boardroom/02.png"],
    links: [],
  },
  {
    category: "freelance",
    slug: "urp-lighting",
    title: "Built-in URP로 변경후 라이팅 작업",
    status: "개발완료",
    tags: ["3D", "백뷰", "어드벤처", "Unity", "URP", "Lighting"],
    purpose: "외주",
    period: "2024.09.20 ~ 2024.09.23",
    team: "프로그래밍",
    summary: "Built-in 프로젝트를 URP로 변경한 뒤 라이팅과 포스트프로세싱을 조정했습니다.",
    role: "URP 전환, RealToon 변환 적용, 포스트프로세싱 톤 조정을 담당했습니다.",
    problem: "Built-in 파이프라인에 맞춰진 셰이더와 조명 톤이 URP에서 그대로 작동하지 않았습니다.",
    solution: "URP에 맞게 쉐이더를 변환하고 게임 톤에 맞춰 후처리 값을 다시 잡았습니다.",
    learned: "렌더 파이프라인 전환은 단순 설정 변경이 아니라 머티리얼, 셰이더, 후처리를 함께 확인해야 합니다.",
    image: "assets/works/urp-lighting/01.png",
    gallery: ["assets/works/urp-lighting/01.png", "assets/works/urp-lighting/02.png"],
    links: [],
  },
  {
    category: "study",
    slug: "graphics-basic",
    title: "게임그래픽엔진기초",
    status: "개발완료",
    tags: ["3D", "과제", "Lighting", "Unity", "URP"],
    purpose: "게임그래픽엔진기초 기말과제",
    period: "",
    team: "1명",
    summary: "1300년대 조선을 표현하기 위한 배치와 라이트 작업입니다.",
    role: "씬 배치와 라이트를 담당했습니다.",
    problem: "게임 화면이라면 플레이어의 시선이 어디로 유도될지 고려해야 했습니다.",
    solution: "채도 높은 색과 푸른 하늘을 사용하고, 시선 흐름을 의식하며 배치했습니다.",
    learned: "라이팅과 배치는 분위기뿐 아니라 플레이어의 시선 유도에도 직접적인 영향을 준다는 점을 배웠습니다.",
    image: "assets/works/graphics-basic/01.png",
    gallery: ["assets/works/graphics-basic/01.png"],
    links: [{ label: "영상", url: "https://youtu.be/xHi0siHwVas" }],
  },
  {
    category: "study",
    slug: "graphics-practice",
    title: "게임그래픽엔진활용",
    status: "개발완료",
    tags: ["3D", "과제", "Lighting", "Unity", "Unreal"],
    purpose: "게임그래픽엔진활용 과제",
    period: "",
    team: "",
    summary: "중간/기말 과제로 진행한 배치와 라이트 작업입니다.",
    role: "씬 배치, 라이트, 포그 분위기 조정을 담당했습니다.",
    problem: "사막 분위기를 만들기 위해 건조함과 모래 폭풍 같은 공기감을 표현해야 했습니다.",
    solution: "구름을 줄이고 포그를 진하게 설정해 모래 폭풍이 온 듯한 분위기를 만들었습니다.",
    learned: "포그와 하늘 상태만으로도 공간의 기후와 감정이 크게 달라진다는 점을 배웠습니다.",
    image: "assets/works/graphics-practice/01.png",
    gallery: ["assets/works/graphics-practice/01.png", "assets/works/graphics-practice/02.png"],
    links: [],
  },
  {
    category: "study",
    slug: "graphics-advanced",
    title: "게임그래픽엔진심화",
    status: "개발완료",
    tags: ["3D", "과제", "Unreal", "Deferred"],
    purpose: "게임그래픽엔진심화 과제",
    period: "",
    team: "1명",
    summary: "Unreal 기반 그래픽 엔진 심화 과제 결과물입니다.",
    role: "Unreal 씬 구성과 발표용 결과 이미지 제작을 진행했습니다.",
    problem: "결과물을 발표 가능한 이미지와 영상으로 정리해야 했습니다.",
    solution: "장면별 슬라이드 이미지를 구성하고 영상 링크로 결과물을 확인할 수 있게 정리했습니다.",
    learned: "작업물은 구현뿐 아니라 보여주는 방식까지 정리해야 포트폴리오 가치가 높아진다는 점을 배웠습니다.",
    image: "assets/works/graphics-advanced/01.png",
    gallery: ["assets/works/graphics-advanced/01.png", "assets/works/graphics-advanced/02.png"],
    links: [{ label: "영상", url: "https://youtu.be/U_xqcMW0Et4" }],
  },
  {
    category: "study",
    slug: "vfx",
    title: "게임이펙트제작",
    status: "개발완료",
    tags: ["3D", "VFX", "과제", "Unity", "URP"],
    purpose: "게임이펙트제작 과제",
    period: "2024.05.01 ~ 2024.06.11",
    team: "1명",
    summary: "라이트닝, 마법스킬, 피격 이펙트 제작 과제입니다.",
    role: "여러 전투 상황에 맞는 이펙트 시퀀스를 제작했습니다.",
    problem: "각 이펙트가 기능적으로 구분되면서도 같은 게임 톤 안에 있어야 했습니다.",
    solution: "라이트닝, 마법, 피격 상황별로 형태와 타이밍을 나눠 제작했습니다.",
    learned: "이펙트는 모양뿐 아니라 등장 타이밍과 지속시간이 타격감에 큰 영향을 준다는 점을 배웠습니다.",
    image: "assets/works/vfx/01.png",
    gallery: ["assets/works/vfx/01.png"],
    links: [],
  },
  {
    category: "study",
    slug: "watercolor-shader",
    title: "수채화 쉐이더 작업",
    status: "개발완료",
    tags: ["3D", "Shader", "Unity", "Built-in", "VRC"],
    purpose: "VRC에서 작동하는 수채화 느낌 쉐이더 제작",
    period: "",
    team: "",
    summary: "포스트프로세싱 방식과 기본 머티리얼 쉐이더 방식으로 제작한 수채화 쉐이더입니다.",
    role: "렌더 이미지를 메테리얼 파라미터로 활용하는 수채화 쉐이더를 제작했습니다.",
    problem: "VRC 환경에서 작동해야 해서 Built-in 파이프라인 제약을 고려해야 했습니다.",
    solution: "PP 방식과 기본 머티리얼 쉐이더 방식을 나눠 제작했습니다.",
    learned: "목표 플랫폼의 렌더링 제약을 먼저 확인해야 쉐이더 제작 방향을 빠르게 정할 수 있습니다.",
    image: "assets/works/watercolor-shader/01.png",
    gallery: ["assets/works/watercolor-shader/02.gif", "assets/works/watercolor-shader/01.png"],
    links: [{ label: "참고 자료", url: "http://www.shaderslab.com/demo-63---oil-painting.html" }],
  },
  {
    category: "study",
    slug: "material-tool",
    title: "메테리얼 파라미터 설정 자동화 툴",
    status: "개발완료",
    tags: ["Tool", "Shader", "Editor", "Unity"],
    purpose: "팀 프로젝트에서 메테리얼 파라미터를 한번에 수정하기 위함",
    period: "2025.09.07",
    team: "1명",
    summary: "쉐이더 파라미터 값을 여러 메테리얼에 한번에 적용하는 Unity 에디터 툴입니다.",
    role: "대상 메테리얼 검색, 파라미터 선택, 미리보기, Undo 가능한 적용 흐름을 구현했습니다.",
    problem: "같은 쉐이더를 쓰는 여러 메테리얼의 값을 반복 수정해야 했습니다.",
    solution: "Shader All Materials, Selected Materials, Dragged Materials 세 범위를 제공하는 에디터 창을 만들었습니다.",
    learned: "반복 작업을 툴로 바꾸면 팀 전체의 수정 비용과 실수를 줄일 수 있다는 점을 배웠습니다.",
    image: "assets/works/material-tool/01.png",
    gallery: ["assets/works/material-tool/01.png", "assets/works/material-tool/02.png"],
    links: [],
  },
  {
    category: "study",
    slug: "cloud-forest-shadow",
    title: "구름 그림자 및 숲 그림자 쉐이더",
    status: "진행 중",
    tags: ["3D", "Shader", "Lighting", "Unity"],
    purpose: "청강대 졸업작품을 위한 쉐이더",
    period: "",
    team: "",
    summary: "숲과 구름 그림자를 표현하기 위한 R&D 쉐이더 작업입니다.",
    role: "RenderTexture와 CustomRenderTexture를 활용한 그림자 표현 방식을 연구했습니다.",
    problem: "기존 숲 그림자 표현 방식이 좋지 않았고, 나뭇잎이 만드는 그림자처럼 보여야 했습니다.",
    solution: "Sine 기반 흔들림과 Directional Light Cookie 방식을 실험했습니다.",
    learned: "쉐이더 R&D에서는 임시 리소스와 최종 아트 리소스의 차이를 분리해 판단해야 한다는 점을 배웠습니다.",
    image: "assets/works/cloud-forest-shadow/01.png",
    gallery: ["assets/works/cloud-forest-shadow/01.png", "assets/works/cloud-forest-shadow/02.png", "assets/works/cloud-forest-shadow/03.png"],
    links: [],
  },
  {
    category: "study",
    slug: "random-tiling",
    title: "바닥 랜덤타일링 쉐이더",
    status: "개발완료",
    tags: ["Shader", "UV", "Texture", "Unity"],
    purpose: "타일링 되는 바닥 텍스처 UV를 맞춰 제작",
    period: "",
    team: "",
    summary: "최대 4개 텍스처를 월드 기준으로 랜덤 타일링하는 바닥 쉐이더입니다.",
    role: "해시 함수 기반 랜덤 선택과 월드 기준 UV 타일링을 구현했습니다.",
    problem: "오브젝트마다 텍스처 크기가 달라지면 바닥 타일 크기가 일정하지 않았습니다.",
    solution: "월드 기준 UV를 사용해 어디서든 동일한 타일 크기가 나오도록 만들었습니다.",
    learned: "월드 공간을 기준으로 삼으면 배치가 바뀌어도 시각적 일관성을 유지할 수 있다는 점을 배웠습니다.",
    image: "assets/works/random-tiling/01.png",
    gallery: ["assets/works/random-tiling/01.png", "assets/works/random-tiling/02.png", "assets/works/random-tiling/03.png"],
    links: [],
  },
  {
    category: "study",
    slug: "water-form",
    title: "물 쉐이더에 form 파트 추가",
    status: "개발완료",
    tags: ["3D", "Shader", "Water", "Unity", "URP"],
    purpose: "졸업작품 물 쉐이더에 캐주얼한 foam 표현 추가",
    period: "",
    team: "",
    summary: "URP 물 쉐이더에 캐주얼한 foam 표현을 추가한 작업입니다.",
    role: "무료 URP 물 쉐이더를 기반으로 게임 톤에 맞는 foam 파트를 추가했습니다.",
    problem: "게임은 캐주얼한 톤인데 기존 물 표현은 그 느낌과 맞지 않았습니다.",
    solution: "기존 물 쉐이더를 유지하면서 foam 표현을 추가해 톤을 맞췄습니다.",
    learned: "기존 에셋을 활용하더라도 프로젝트 아트 방향에 맞게 필요한 부분을 직접 보강해야 합니다.",
    image: "assets/works/water-form/01.png",
    gallery: ["assets/works/water-form/01.png", "assets/works/water-form/02.png", "assets/works/water-form/03.png"],
    links: [],
  },
];

window.PORTFOLIO_PROJECTS = window.PORTFOLIO_ITEMS.filter((item) => item.category === "project");
window.PORTFOLIO_FREELANCE = window.PORTFOLIO_ITEMS.filter((item) => item.category === "freelance");
window.PORTFOLIO_STUDIES = window.PORTFOLIO_ITEMS.filter((item) => item.category === "study");
