window.PORTFOLIO_CONTENT = {
  "dear-my-prince": [
    { type: "h3", text: "PM 및 통합 작업" },
    { type: "p", text: "PM으로 파트별 진행 상황과 일정을 확인하고 작업 우선순위를 조율했습니다. 프로그래밍, 애니메이션, 쉐이더, 이펙트, 사운드 결과물이 한 플레이 흐름에서 동작하도록 테스트와 통합 작업을 함께 진행했습니다." },
    { type: "h3", text: "플레이어와 게임 로직" },
    { type: "p", text: "플레이어의 기본 공격 콤보와 대쉬 공격, 피격 무적, 벽 감지와 벽 이동, 아래 점프를 구현했습니다. Spline을 이용한 앞뒤 Z축 이동과 진입 방향에 따라 통과 여부를 판단하는 One Way Platform, 부서지는 벽과 낙하 시 리스폰 같은 스테이지 기믹도 제작했습니다." },
    { type: "p", text: "몬스터 공통 Base와 BT 구조를 만들고 Ira, Nuovo, Scopi의 이동·추적·공격·스턴·캐치·그로기 상태를 연결했습니다. 카메라 매니저, ScriptableObject 기반 카메라 설정, 바운더리와 타겟 그룹을 구현하고 Z축 이동과 전투 상황에 맞춰 카메라 동작을 조정했습니다." },
    { type: "h3", text: "애니메이션 제작 및 시스템" },
    { type: "p", text: "기존 커스텀 애니메이션 방식을 Unity Animator 기반으로 전환하고, 좌우 방향 애니메이션을 Blend Tree로 연결했습니다. 플레이어 공격·대쉬·점프·랜딩과 몬스터 애니메이션을 적용하고 이벤트 연결과 전환 버그를 수정했습니다." },
    { type: "p", text: "직접 제작한 애니메이션에는 플레이어 벽점프의 착지·슬라이딩·점프 동작, 비전투 Idle, Scopi의 걷기와 캐치, 부서지는 벽 동작이 포함됩니다. 벽점프는 착지부터 슬라이딩 준비, 루프, 점프까지 한 흐름으로 제작하고 발 위치와 허리·목 각도, 재생 속도를 폴리싱했습니다." },
    { type: "h3", text: "URP 툰 쉐이더 및 그래픽 기술" },
    { type: "p", text: "캐릭터와 배경에 사용할 URP 툰 쉐이더를 제작했습니다. Toon Lighting과 Outline Pass를 구성하고 색상, 명암 단계, Specular, Normal, Outline을 머티리얼에서 조절할 수 있도록 만들었습니다." },
    { type: "image", src: "assets/works/dear-my-prince/face-sdf.png", caption: "빛 방향과 SDF 맵을 이용한 얼굴 그림자 계산" },
    { type: "p", text: "캐릭터 얼굴에는 빛 방향에 따라 전환되는 SDF 그림자를 추가했고, 피격 표현에는 화면 깊이와 Fresnel을 조합한 Rim Light를 적용했습니다. 몬스터의 피격과 사망에는 Dissolve와 Fresnel 표현을 제작했습니다." },
    { type: "image", src: "assets/works/dear-my-prince/rim-light.png", caption: "깊이와 Fresnel을 이용한 Rim Light 계산" },
    { type: "image", src: "assets/works/dear-my-prince/monster-dissolve-fresnel.png", caption: "몬스터 Dissolve와 Fresnel Shader Graph" },
    { type: "p", text: "카메라와 플레이어 사이를 가리는 벽에는 거리 기반 Dithering을 추가하고, 필요하면 슬라이더 값으로 전체 투명도를 제어할 수 있게 했습니다. 이외에도 월드 기준 랜덤 바닥 타일링, 물 쉐이더, 라이팅과 머티리얼 조정 작업을 진행했습니다." },
    { type: "image", src: "assets/works/dear-my-prince/dithering.png", caption: "카메라 거리 기반 Dithering 처리" },
    { type: "h3", text: "이펙트 및 사운드" },
    { type: "p", text: "플레이어 공격과 몬스터 피격·스턴 이펙트를 적용하고 위치, 크기, 재생 타이밍과 Lifetime을 조정했습니다. 애니메이션 이벤트와 공격 시스템이 이펙트를 정확한 프레임에 호출하도록 연결했습니다." },
    { type: "p", text: "FMOD Manager를 인터페이스 기반으로 구성하고 Unity 프로젝트에 연동했습니다. Audio Type별 볼륨과 BGM 목록을 관리하고 플레이어와 몬스터의 공격, 대쉬, 캐치, 피격 등 SFX를 애니메이션 및 게임 로직에 연결했습니다." },
  ],
  "capstone-lighting": [
    { type: "p", text: "VRC에서의 최적화, 라이팅, 머티리얼 작업, 베이킹 등의 전반적인 작업을 하였습니다." },
    { type: "image", src: "assets/works/capstone-lighting/01.png", caption: "캡스톤Lighting 대표 화면" },
    { type: "h3", text: "디렉셔널 라이트 문제" },
    { type: "p", text: "VRChat 게임의 맵은 Scene 한 개에서만 제작해야 한다는 단점이 있습니다. 한 씬 안에 5개의 구역을 만들다 보니 각 구역에 알맞은 라이트 세팅이 모두 달랐고, 디렉셔널 라이트는 1개라 절충이 필요했습니다." },
    { type: "image", src: "assets/works/capstone-lighting/02.png", caption: "구역별 라이팅 작업" },
    { type: "h3", text: "다른 구역이 화면에 보이는 문제" },
    { type: "p", text: "창문 너머로 다른 구역이 보여 몰입도가 떨어지는 문제가 있었습니다. 이 문제는 카메라의 Far, Near 값을 변경하여 해결했습니다." },
    { type: "image", src: "assets/works/capstone-lighting/03.png", caption: "창문과 구역 노출 문제 확인" },
    { type: "p", text: "외주 라이팅 작업을 하면서 자주 나온 문제는 Generate Lightmap UV였습니다. 이 기능을 켜지 않으면 한 모델링을 여러 개 복사해 제작할 때 베이크맵이 겹쳐 만들어지기 때문에 꼭 체크가 필요했습니다." },
    { type: "p", text: "일부 구역에서는 벽의 디렉셔널 라이트 그림자를 없애야 했고, Cast Shadows와 Receive Shadows를 꺼서 문제를 해결했습니다." },
    { type: "image", src: "assets/works/capstone-lighting/04.png", caption: "그림자 옵션 조정 결과" },
  ],
  tabibuntu: [
    { type: "p", text: "게임에서 스페셜 코인을 먹으면 UI가 나오도록 만들었습니다. 게임매니저를 호출하고, UI 애니메이션을 활용하여 텍스트와 UI Image만 변경하면 되도록 작업했습니다." },
    { type: "image", src: "assets/works/tabibuntu/01.png", caption: "스페셜 코인 UI" },
    { type: "p", text: "스페셜 코인을 획득하면 플레이어가 이미지를 해금하고 이후에도 계속 볼 수 있어야 했기 때문에 저장과 불러오기가 필요했습니다. 간단하게 만들 수 있는 PlayerPrefs를 사용하여 저장과 불러오기를 제작했습니다." },
    { type: "h3", text: "그래플링" },
    { type: "p", text: "고군분투 게임의 핵심인 그래플링을 구현하기 위해 로프를 사용해 물리로 제작할지, 미리 시뮬레이션한 값을 재생할지 고민했습니다. 원작의 매커니즘을 다시 플레이하며 확인한 결과 물리적으로 표현하는 방식으로 구현했습니다." },
    { type: "h3", text: "타일맵 기반 코인 생성" },
    { type: "p", text: "러너 게임에서는 코인이 매우 많기 때문에 하나하나 배치하면 오래 걸리고 수정하기 어렵다고 판단했습니다. 타일맵으로 찍어둔 타일을 Start 함수에서 코인으로 변경하는 클래스를 작성했습니다." },
    { type: "image", src: "assets/works/tabibuntu/02.png", caption: "타일맵을 이용해 코인을 찍어 둔 모습" },
    { type: "p", text: "배경도 같은 방식으로 만들 수 있었지만, 스테이지가 있는 구조가 아니고 세밀한 거리 조절이 어려워 레벨디자인 관점에서 배경은 직접 제작하는 방식으로 판단했습니다." },
  ],
  "accessibility-showroom": [
    { type: "p", text: "다양한 장애인을 위한 제품 전시장 작업입니다. 라이팅 및 머티리얼 생성, 적용을 담당했습니다." },
    { type: "image", src: "assets/works/accessibility-showroom/01.png", caption: "전시장 전체 분위기" },
    { type: "p", text: "전시장 조명이 많이 사용되어 Light를 많이 배치하게 되었는데, 기존 Forward 파이프라인은 8개의 동적 라이트만 지원하는 문제가 있었습니다." },
    { type: "image", src: "assets/works/accessibility-showroom/02.png", caption: "전시장 내부 라이팅" },
    { type: "p", text: "Forward+ 파이프라인을 사용하여 많은 동적 라이트를 사용할 수 있게 했습니다. 그림자 부분이 너무 어둡지 않게 조정한 부분은 의뢰자의 요청과 VR 기기라는 플랫폼에 맞춰 필요한 부분에만 그림자를 넣기 위한 선택이었습니다." },
    { type: "image", src: "assets/works/accessibility-showroom/03.png", caption: "제품 전시 구역" },
  ],
  "et-boardroom": [
    { type: "p", text: "하나의 씬 라이팅 및 머티리얼 생성과 적용을 진행한 외주 작업입니다." },
    { type: "image", src: "assets/works/et-boardroom/01.png", caption: "ET BordRoom 대표 화면" },
    { type: "p", text: "작업 방식은 장애인 기구 전시장 제작과 동일했습니다. 클라이언트분께서 원하시는 구도와 라이팅이 있었기 때문에, 해당 기준에 맞춰 라이트 배치와 머티리얼 톤을 제작했습니다." },
    { type: "image", src: "assets/works/et-boardroom/02.png", caption: "라이팅과 머티리얼 적용 화면" },
  ],
  "urp-lighting": [
    { type: "p", text: "Built-in 파이프라인의 프로젝트를 URP로 변경한 후, RealToon을 URP에 맞게 변환하여 적용하고 게임의 톤에 맞게 포스트프로세싱 작업을 했습니다." },
    { type: "image", src: "assets/works/urp-lighting/01.png", caption: "URP 변경 후 화면" },
    { type: "image", src: "assets/works/urp-lighting/02.png", caption: "라이팅과 포스트프로세싱 조정" },
  ],
  "graphics-basic": [
    { type: "p", text: "게임그래픽엔진기초 기말 결과물입니다. 배치 및 라이트만 작업한 작업물입니다." },
    { type: "p", text: "1300년대 조선을 나타내고자 하여 채도를 높게 가져갔고, 하늘 또한 푸르게 작업했습니다." },
    { type: "image", src: "assets/works/graphics-basic/01.png", caption: "게임그래픽엔진기초 기말 결과물" },
    { type: "p", text: "배치를 하면서 만약 이게 게임이라면 플레이어의 시선이 어떻게 유도될지 의도를 담으면서 작업하려고 노력했습니다." },
  ],
  "graphics-practice": [
    { type: "h3", text: "중간 과제" },
    { type: "image", src: "assets/works/graphics-practice/01.png", caption: "중간 과제 결과물" },
    { type: "h3", text: "기말 과제" },
    { type: "image", src: "assets/works/graphics-practice/02.png", caption: "기말 과제 결과물" },
    { type: "p", text: "배치 및 라이트만 작업한 작업물입니다. 사막을 표현하기 위해 구름은 없고, 모래 폭풍이 온 것 같은 분위기를 의도하여 포그를 진하게 깔았습니다." },
  ],
  "graphics-advanced": [
    { type: "p", text: "게임그래픽엔진심화 과제 결과물입니다. Unreal 기반으로 장면을 구성하고 발표용 이미지와 영상을 정리했습니다." },
    { type: "image", src: "assets/works/graphics-advanced/01.png", caption: "게임그래픽엔진심화 결과 이미지 1" },
    { type: "image", src: "assets/works/graphics-advanced/02.png", caption: "게임그래픽엔진심화 결과 이미지 2" },
  ],
  vfx: [
    { type: "p", text: "게임이펙트제작 과제입니다. 라이트닝, 마법스킬, 피격 이펙트를 제작했습니다." },
    { type: "image", src: "assets/works/vfx/01.png", caption: "게임이펙트제작 결과 이미지" },
  ],
  "watercolor-shader": [
    { type: "p", text: "VRC에서 작동하기 위해 Built-in 쉐이더로 제작했습니다." },
    { type: "image", src: "assets/works/watercolor-shader/02.gif", caption: "수채화 쉐이더 동작 화면" },
    { type: "p", text: "포스트프로세싱으로 제작하는 방식과 기본 메테리얼 쉐이더로 제작하는 방식, 두 가지를 만들었습니다." },
    { type: "image", src: "assets/works/watercolor-shader/01.png", caption: "수채화 쉐이더 결과 이미지" },
    { type: "p", text: "렌더 이미지를 만들어 메테리얼에 값을 넣어주는 파라미터 등을 활용했습니다." },
  ],
  "material-tool": [
    { type: "h3", text: "개요" },
    { type: "p", text: "메테리얼 파라미터 값을 한번에 수정하기 위해 만든 자동화 툴입니다." },
    { type: "image", src: "assets/works/material-tool/01.png", caption: "TA/ShaderParamEditWindow 메뉴" },
    { type: "p", text: "TA/ShaderParamEditWindow를 눌러 창을 켤 수 있습니다." },
    { type: "image", src: "assets/works/material-tool/02.png", caption: "쉐이더 파라미터 선택 화면" },
    { type: "p", text: "쉐이더를 넣으면 해당 쉐이더의 파라미터들이 나오게 됩니다. 수정할 파라미터를 체크하고 적용 범위를 선택합니다." },
    { type: "p", text: "적용 범위는 Shader All Materials, Selected Materials, Dragged Materials로 나뉩니다. 대상 미리보기 버튼으로 대상 메테리얼을 확인할 수 있고, 적용 후 Undo(Ctrl + Z)를 할 수 있습니다." },
    { type: "p", text: "쉐이더의 기본값을 수정하기 위해 Shader 기본값 저장 버튼도 만들었습니다." },
  ],
  "cloud-forest-shadow": [
    { type: "p", text: "우리 게임 숲의 그림자를 표현하기 위한 기존 방법이 좋지 않아 R&D 및 제작을 진행했습니다." },
    { type: "image", src: "assets/works/cloud-forest-shadow/01.png", caption: "구름 그림자 및 숲 그림자 쉐이더" },
    { type: "h3", text: "숲 쉐이더" },
    { type: "image", src: "assets/works/cloud-forest-shadow/02.png", caption: "숲 그림자 쉐이더 테스트" },
    { type: "p", text: "Sine을 이용해 흔들림을 표현했습니다. 아쉬운 점은 그림자가 좀 더 Sin 노이즈를 통해 흔들리면 좋을 것 같다는 점입니다." },
    { type: "p", text: "SineSpeed는 정해진 Sine 크기를 왕복하는 스피드이고, MaxMoveSize는 Sine 크기를 얼마나 할지 정하는 값입니다." },
    { type: "p", text: "구현 방식은 RenderTexture를 사용했고, CustomRenderTexture에 메테리얼을 넣은 뒤 Directional Light의 Cookie에 넣어 사용했습니다. Size 및 적당한 스피드를 찾아야 합니다." },
    { type: "p", text: "현재 임의로 만든 Forest는 숲의 나뭇잎이 만들어내는 그림자 같지 않아 원화 쪽에서 이미지 제작이 필요하다고 판단했습니다." },
    { type: "image", src: "assets/works/cloud-forest-shadow/03.png", caption: "ForestShadow Mask" },
    { type: "p", text: "추가로 FogLightController를 수정하여 Cookie 값을 바꾸는 코드를 추가할 예정입니다." },
  ],
  "random-tiling": [
    { type: "h3", text: "작업 목표" },
    { type: "p", text: "타일링 되는 바닥의 텍스처 UV를 맞춰서 제작해주는 쉐이더입니다." },
    { type: "h3", text: "작업 내용" },
    { type: "image", src: "assets/works/random-tiling/01.png", caption: "최대 4개의 텍스처를 타일링하도록 제작" },
    { type: "p", text: "최대 4개의 텍스처를 타일링할 수 있도록 제작했습니다." },
    { type: "image", src: "assets/works/random-tiling/02.png", caption: "랜덤하게 작동하도록 하는 해시 함수" },
    { type: "p", text: "랜덤하게 작동할 수 있도록 해시 함수를 사용했습니다. 버텍스 쉐이더에서는 타일링할 UV 정도를 가져옵니다." },
    { type: "image", src: "assets/works/random-tiling/03.png", caption: "월드 기준 타일링" },
    { type: "p", text: "월드에 맞게 타일링되도록 작업했습니다. 어디든 동일한 타일 크기를 가져가게 하기 위해서입니다. 트리거를 통해 조작도 가능하게 제작해두었습니다." },
  ],
  "water-form": [
    { type: "p", text: "청강대 졸업작품에 들어가는 물 쉐이더에서 캐주얼한 foam 파트를 추가한 작업입니다." },
    { type: "image", src: "assets/works/water-form/01.png", caption: "물 쉐이더 전체 화면" },
    { type: "p", text: "Unity URP에 있는 물 쉐이더에 추가로 작업했습니다. 졸업작품을 하는 데 있어 한정된 시간에 높은 퀄리티를 얻을 수 있는 무료 에셋이라고 생각했기 때문입니다." },
    { type: "p", text: "foam을 추가한 이유는 게임은 캐주얼한데 물이 그러한 느낌이 나지 않아서입니다." },
    { type: "image", src: "assets/works/water-form/02.png", caption: "foam 파트 추가 화면" },
    { type: "image", src: "assets/works/water-form/03.png", caption: "물 쉐이더 디테일" },
  ],
};
